### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by hrecht** [nyphilarchive/PerformanceHistory#14]
Hello, thanks for continuing to update this great dataset.
There are a few broken links in the README. The links pointing to http://nyphil.org/history/performance-history/help lead to a 404 error page. These links are in field reference table of the README, in the Description column for the Orchestra and eventType rows.

(Can't seem to link to line numbers in a Github .md file, would if I could.)

**Comment by nyphil** [comment]
Fixed; please pardon the delay, and thanks for letting us know!
