### ISSUE TITLE
Bad Encoding

### ISSUE THREAD

**Issue by archy-bold** [nyphilarchive/PerformanceHistory#3]
I've noticed that the encoding seems to have garbled the accented characters.

For example, Frédéric Chopin appears in the data as `Chopin,  FrÃ©dÃ©ric`.

Great repository, otherwise!

**Comment by mjbrodsky** [comment]
Thanks! All diacritics are coming through fine for me...can you be more specific about where you're seeing this (file/line no.) and how you're viewing the data?

**Comment by hamlet82** [comment]
I know my facility with Python encoding is abysmal, so the problem (once located) is almost certainly on my end.

**Comment by mjbrodsky** [comment]
I just found an example...line 16610 of complete.xml. I'll check what's in our Solr index, since that's where this data is originating. Possible that I need to re-index some records.

**Comment by archy-bold** [comment]
Should have been more specific, there, didn't realise some of them were encoded ok.

There are other examples in the data. Searching for the character `Ã` is always a sure fire way of locating them.

**Comment by mjbrodsky** [comment]
The issue was with the migration from our database of record into the Alfresco repo. Made fix in migration config and re-migrated metadata so this is gremlin is now removed.
