### ISSUE TITLE
Unescaped ampersands (&) causing XML parse errors

### ISSUE THREAD

**Issue by archy-bold** [nyphilarchive/PerformanceHistory#6]
The XML is causing errors in most parsers due to ampersands (&) not being escaped correctly.

See line 13611 of `1842-43_TO_1910-11.xml`:

`<workTitle>TOCCATA & FUGUE, D MINOR, BWV 565 (PIANO) (ARR. Tausig)</workTitle>`

Should read:

`<workTitle>TOCCATA &amp; FUGUE, D MINOR, BWV 565 (PIANO) (ARR. Tausig)</workTitle>`

**Comment by mjbrodsky** [comment]
My source XML does contain `&amp;` but it is getting replaced with `&` in the Python re-write.

@hamlet82 (or anyone else), do you know of any quick way to tell this script not to interpret this HTML character code when writing the new file? Basically we want the `&amp;` to be output as `&amp;`

**Comment by mjbrodsky** [comment]
@hamlet82 fix did the trick.
